vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      
  deploy:
    docker:
      - image: willhallonline/ansible:2.9-alpine
    steps:
      - attach_workspace:
         at: .
      - run:
          command: pip install boto boto3
      - run:
          command: ansible-playbook ./ansible/ec2_deploy.yml

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build