- name: Terminate running EC2 instances
  hosts: localhost
  connection: local
  vars:
    access_key: ASIA3FKSKWME33G637GD
    secret_key: F8ZdZadklSxECFZE6ap8Bmr4HnVBRKOs0mhV973U
    token: FwoGZXIvYXdzEJz//////////wEaDO1IHDWqWNv3t6HxlyLFARPeCgFNdzi23EKPTHq1jF1A7tVtf+4z2Zlj/03OzJwe+wJcfEXqu9ljTSQmzDsa7ujEvPGtPVOLnaVn9zy0Vv826wgSE4DfQB2U6xfF52sPjkJb1n0M1cDQ3nI2Ez9z16alLbpDlsWIiFg8hT2dF+MSjxKz0vAYyHhkjZ4BDdYpJqWfPfG1+7xTlE8OPqeyi03sgEe7+x22BMR9PvxoGf+H2Wbuu1n1+A3xHC1vMO1mDgilIskeG1abt6k+0aneG3rRKKx5KMHUifYFMi24YZIl/IzF2q1+PZ+5+iUg/SNxoIo+asowlCIHrYBo8CZp119aOeg2o8OfJo0=

  tasks:
    - name: Get running instances
      ec2_instance_info:
        region: us-east-1        
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
        filters:
          "tag:app": eshop
      register: ec2_instance_info

    - name: Display info
      debug: msg='{{item.instance_id}}'
      with_items: '{{ec2_instance_info.instances}}'

    - name: Terminate instances
      ec2:
        region: us-east-1
        key_name: aws-key-pair
        instance_ids: '{{item.instance_id}}'
        state: 'absent'
        wait: yes        
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
      with_items: '{{ec2_instance_info.instances}}'