- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: aws-key-pair
        vpc_subnet_id: subnet-11619177
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: "ASIA3FKSKWMESGIKYMOA"
        aws_secret_key: "t9+mG3XQNmzDuFJlSfMaR/MrXVMvoBIvWnmaudX8"
        security_token: "FwoGZXIvYXdzED4aDEB/Jm6nDFCGCMHwfiLFAbtSpwbH4mtYrvl098F5TXWzuvzE5wiuVuG8wGm2aRYvoGrgjdiEah4MmLekoiLUUPjRvRKAwv5Km5FK3mFKwDPsp3yO2CMxKYxK5asJKEaPjl1BV9ItbVtFINxPhHb7b+d5FE9x/EPY0rBJAXQ2uwqkuaZvdxbI/737bVxS7VnSwMeXqd0YL+C9Ve/UsBIdCeoYr988SaV2TAg+b3y6pQ4i9u2TjIH8jKG+M8IQilFg0rA7xvVlvkBiKI2f9haot16BievxKLb99PUFMi1ScXAqkuLRaXgt9cGqdgGSJ3UOA7vTBVeYFx6y3+K2VwYVx4NPy00emJSWoxo="
      register: ec2
      
    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt: 
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from git
      git: 
        repo: 'https://github.com/smad00/4IT572_projekt.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes
    - wait_for: 
        port: 80