- name: Terminate running EC2 instances
  hosts: localhost
  connection: local
  vars:
    access_key: ASIA3FKSKWMESGIKYMOA
    secret_key: t9+mG3XQNmzDuFJlSfMaR/MrXVMvoBIvWnmaudX8
    token: FwoGZXIvYXdzED4aDEB/Jm6nDFCGCMHwfiLFAbtSpwbH4mtYrvl098F5TXWzuvzE5wiuVuG8wGm2aRYvoGrgjdiEah4MmLekoiLUUPjRvRKAwv5Km5FK3mFKwDPsp3yO2CMxKYxK5asJKEaPjl1BV9ItbVtFINxPhHb7b+d5FE9x/EPY0rBJAXQ2uwqkuaZvdxbI/737bVxS7VnSwMeXqd0YL+C9Ve/UsBIdCeoYr988SaV2TAg+b3y6pQ4i9u2TjIH8jKG+M8IQilFg0rA7xvVlvkBiKI2f9haot16BievxKLb99PUFMi1ScXAqkuLRaXgt9cGqdgGSJ3UOA7vTBVeYFx6y3+K2VwYVx4NPy00emJSWoxo=

  tasks:
    - name: Get running instances
      ec2_instance_info:
        region: us-east-1        
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
        filters:
          "tag:app": eshop
      register: ec2_instance_info

    - name: Terminate instances
      ec2:
        region: us-east-1
        key_name: aws-key-pair
        instance_ids: '{{item.instance_id}}'
        state: 'absent'
        wait: yes
        with_items: '{{ec2_instance_info.instances}}'
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"