- name: Terminate running EC2 instances
  hosts: localhost
  connection: local
  vars:
    access_key: ASIA3FKSKWME4T6FEP7M
    secret_key: 4G4eJwW/RUDtoxquVbTpxIbY6uzjO9bzLizU1mkk
    token: FwoGZXIvYXdzEHQaDND5v42/7TrcoNDDdyLFAXk8MNcCzZ2+/Oj9hlDvqLdbmwbXl8Xw3EgePIQxHG757bXF3txP5zOfjg01Iz6ion5ZVp2zigIJAggE+qX+JaVju36e90PDCkVxJ2Y+7tcCQrkWCLoNpnuysrg2NZQhIhEJOIScrj61MCBSHSizqXu8c9NQu4KLwlK7mdRjctD1rDdZ5hM2xX3gJjR68W9KpwA4GFebLSib1IRtPVQjK7RP8kf0OuFh5y4HbdoUUA2qYj5U27XPnidOAIGmoBBiwXT11g1HKPLvgPYFMi3hjYaWersGs7BqRHtY3LQSnq0W5xs9teRy8nso+VhL7xIibqRHwjfADcAlFU4=

  tasks:
    - name: Get running instances
      ec2_instance_info:
        region: us-east-1        
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
        filters:
          "tag:app": eshop
      register: ec2_instance_info

    - name: Display info
      debug: msg='{{item.instance_id}}'
      with_items: '{{ec2_instance_info.instances}}'

    - name: Terminate instances
      ec2:
        region: us-east-1
        key_name: aws-key-pair
        instance_ids: '{{item.instance_id}}'
        state: 'absent'
        wait: yes        
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
      with_items: '{{ec2_instance_info.instances}}'