- name: Deploy to EC2
  hosts: localhost
  connection: local
  vars:
    access_key: ASIA3FKSKWME2ZEO7ZHL
    secret_key: CZPy2KlfCh0/Abmq72OdeB2VVKE3EcftHCHhH2f5
    token: FwoGZXIvYXdzEHAaDOChv0IRKBJd41Vd9iLFARQsWfLhkVv+PcOB80N+sGgvzEIa3x8xB58Iqaz/eGUppd5X890WH+fLfquv59ZGi8F7kdewYP0Ac2Zk0UYkMujWNDlfVswDf6h9OrHFq2XqmCZyeAS0cQ2leenqCnuq/PGC6I/oWH/Y5AleY1bzGwkWnVF+FmO1+QCKy8oTgMHmrgqT279C733xOnkvYP+QrPNB73XS7tOom11b1hzn5mA9u1La0SzJAMIVlr1iTYPJR4bIcY9iKXdRDV3tCS1lFiknXhbUKO3t//UFMi1yF/CEINdoFyRIuyleJi9MXJslaE1eeLtZHTt0orIA67HSgOLMOjHskDouuI0=

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: aws-key-pair
        vpc_subnet_id: subnet-11619177
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        instance_tags:
          app: eshop
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ token }}"
      #register: ec2